### PR TITLE
Update scalar.jl to use muladd

### PR DESCRIPTION
**Pull request by ptiede**
This updates scalar.jl to use muladd generically for `ScaledShiftedLogistic` since https://github.com/JuliaDiff/DiffRules.jl/issues/28 has been merged. I also used `muladd` instead of `fma` since it only uses `fma` if it does give a speed boost. Additionally, I was having issues using Enzyme.jl with fma inserted while everything seems to work fine with muladd.

### CODE REVIEW

**Comment by ptiede** [comment]
The errors seems to be from `ADgradient` not being defined. Is that some versioning issue with LogDensityProblems?

**Comment by tpapp** [comment]
ptiede/TransformVariables.jl#1 should fix CI.

**Comment by tpapp** [comment]
Sorry, it was closed accidentally.

**Review by tpapp — CHANGES_REQUESTED** [review]
Can you please add a test for what was fixed?

Eg a simple logdensity that has a transformation involving `ScaledShiftedExp`, AD with Enzyme, check that `logdensity_and_gradient` is finite.

**Review by tpapp — APPROVED** [review]

**Review by tpapp — APPROVED** [review]
LGTM, thanks!

**Comment by ptiede** [comment]
Sorry for the delay! Holidays happened, and I got stuck with a recent Enzyme bug that just got fixed. Did you want me to add an additional test in another PR?

**Comment by tpapp** [comment]
It is fine as it is, but of course tests are always welcome if you have time. Thanks again for the PR.

**Pull request merged**
